### ISSUE TITLE
Assignment 1 - Ready for Grading

### ISSUE THREAD

**Issue by nickiemitch** [SES-5215-F2020/nmitch-quant#1]
Happy Wednesday,
My assignment 1 is ready for grading at [https://ses-5215-f2020.github.io/nmitch-quant/Assignment-1]. I will submit the CSV on Canvas. 

Have a great evening,
Nickie

**Comment by nickiemitch** [comment]
I just realized that I did not assign this issue to anyone when I submitted it last week. I'm sorry for this oversight.  Please let me know if there's anything you need from me. 

Thanks,
Nickie

**Comment by saratepfer** [comment]
Thank you, Nickie! Nice work. The unit of analysis, sample population, and number of observations are clearly stated, and you correctly identified your categorical and continuous variables.

**Comments on Code**
Lines 18-22 and lines 32-38: These lines are unnecessary because you are only working with household-level data. Otherwise, it's looking good!
